name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [build]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: 💎 setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - run: | 
          npm install -g staticrypt

      - run: bundle install
      - run: bundle lock
      
      - name: Building the website 
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
