name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [build]

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
          
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 💎 setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - run: | 
          npm install -g staticrypt

      - run: bundle install
      - run: bundle lock
      
      - name: Building the website 
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true

      - name: 🚀 Deploying the website 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site